const USER_SESSION_EXPAND =
  "tags, userSessionExercises_via_userSession.exercise.defaultMeasurementType.measurementValues_via_measurementType, userSessionExercises_via_userSession.measurementValue, userSessionExercises_via_userSession.variation, userSessionExercises_via_userSession.tags, meals_via_userSession.tags";
