package migrations

import (
	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"
)

func init() {
	m.Register(func(app core.App) error {
		jsonData := `[
			{
				"createRule": null,
				"deleteRule": null,
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text455797646",
						"max": 0,
						"min": 0,
						"name": "collectionRef",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text127846527",
						"max": 0,
						"min": 0,
						"name": "recordRef",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1582905952",
						"max": 0,
						"min": 0,
						"name": "method",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": true,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": true,
						"type": "autodate"
					}
				],
				"id": "pbc_2279338944",
				"indexes": [
					"CREATE INDEX ` + "`" + `idx_mfas_collectionRef_recordRef` + "`" + ` ON ` + "`" + `_mfas` + "`" + ` (collectionRef,recordRef)"
				],
				"listRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
				"name": "_mfas",
				"system": true,
				"type": "base",
				"updateRule": null,
				"viewRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId"
			},
			{
				"createRule": null,
				"deleteRule": null,
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text455797646",
						"max": 0,
						"min": 0,
						"name": "collectionRef",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text127846527",
						"max": 0,
						"min": 0,
						"name": "recordRef",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cost": 8,
						"hidden": true,
						"id": "password901924565",
						"max": 0,
						"min": 0,
						"name": "password",
						"pattern": "",
						"presentable": false,
						"required": true,
						"system": true,
						"type": "password"
					},
					{
						"autogeneratePattern": "",
						"hidden": true,
						"id": "text3866985172",
						"max": 0,
						"min": 0,
						"name": "sentTo",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": true,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": true,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": true,
						"type": "autodate"
					}
				],
				"id": "pbc_1638494021",
				"indexes": [
					"CREATE INDEX ` + "`" + `idx_otps_collectionRef_recordRef` + "`" + ` ON ` + "`" + `_otps` + "`" + ` (collectionRef, recordRef)"
				],
				"listRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
				"name": "_otps",
				"system": true,
				"type": "base",
				"updateRule": null,
				"viewRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId"
			},
			{
				"createRule": null,
				"deleteRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text455797646",
						"max": 0,
						"min": 0,
						"name": "collectionRef",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text127846527",
						"max": 0,
						"min": 0,
						"name": "recordRef",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text2462348188",
						"max": 0,
						"min": 0,
						"name": "provider",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1044722854",
						"max": 0,
						"min": 0,
						"name": "providerId",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": true,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": true,
						"type": "autodate"
					}
				],
				"id": "pbc_2281828961",
				"indexes": [
					"CREATE UNIQUE INDEX ` + "`" + `idx_externalAuths_record_provider` + "`" + ` ON ` + "`" + `_externalAuths` + "`" + ` (collectionRef, recordRef, provider)",
					"CREATE UNIQUE INDEX ` + "`" + `idx_externalAuths_collection_provider` + "`" + ` ON ` + "`" + `_externalAuths` + "`" + ` (collectionRef, provider, providerId)"
				],
				"listRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
				"name": "_externalAuths",
				"system": true,
				"type": "base",
				"updateRule": null,
				"viewRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId"
			},
			{
				"createRule": null,
				"deleteRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text455797646",
						"max": 0,
						"min": 0,
						"name": "collectionRef",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text127846527",
						"max": 0,
						"min": 0,
						"name": "recordRef",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text4228609354",
						"max": 0,
						"min": 0,
						"name": "fingerprint",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": true,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": true,
						"type": "autodate"
					}
				],
				"id": "pbc_4275539003",
				"indexes": [
					"CREATE UNIQUE INDEX ` + "`" + `idx_authOrigins_unique_pairs` + "`" + ` ON ` + "`" + `_authOrigins` + "`" + ` (collectionRef, recordRef, fingerprint)"
				],
				"listRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
				"name": "_authOrigins",
				"system": true,
				"type": "base",
				"updateRule": null,
				"viewRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId"
			},
			{
				"authAlert": {
					"emailTemplate": {
						"body": "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location.</p>\n<p>If this was you, you may disregard this email.</p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
						"subject": "Login from a new location"
					},
					"enabled": true
				},
				"authRule": "",
				"authToken": {
					"duration": 86400
				},
				"confirmEmailChangeTemplate": {
					"body": "<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Confirm new email</a>\n</p>\n<p><i>If you didn't ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
					"subject": "Confirm your {APP_NAME} new email address"
				},
				"createRule": null,
				"deleteRule": null,
				"emailChangeToken": {
					"duration": 1800
				},
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cost": 0,
						"hidden": true,
						"id": "password901924565",
						"max": 0,
						"min": 8,
						"name": "password",
						"pattern": "",
						"presentable": false,
						"required": true,
						"system": true,
						"type": "password"
					},
					{
						"autogeneratePattern": "[a-zA-Z0-9]{50}",
						"hidden": true,
						"id": "text2504183744",
						"max": 60,
						"min": 30,
						"name": "tokenKey",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"exceptDomains": null,
						"hidden": false,
						"id": "email3885137012",
						"name": "email",
						"onlyDomains": null,
						"presentable": false,
						"required": true,
						"system": true,
						"type": "email"
					},
					{
						"hidden": false,
						"id": "bool1547992806",
						"name": "emailVisibility",
						"presentable": false,
						"required": false,
						"system": true,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "bool256245529",
						"name": "verified",
						"presentable": false,
						"required": false,
						"system": true,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": true,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": true,
						"type": "autodate"
					}
				],
				"fileToken": {
					"duration": 180
				},
				"id": "pbc_3142635823",
				"indexes": [
					"CREATE UNIQUE INDEX ` + "`" + `idx_tokenKey_pbc_3142635823` + "`" + ` ON ` + "`" + `_superusers` + "`" + ` (` + "`" + `tokenKey` + "`" + `)",
					"CREATE UNIQUE INDEX ` + "`" + `idx_email_pbc_3142635823` + "`" + ` ON ` + "`" + `_superusers` + "`" + ` (` + "`" + `email` + "`" + `) WHERE ` + "`" + `email` + "`" + ` != ''"
				],
				"listRule": null,
				"manageRule": null,
				"mfa": {
					"duration": 1800,
					"enabled": false,
					"rule": ""
				},
				"name": "_superusers",
				"oauth2": {
					"enabled": false,
					"mappedFields": {
						"avatarURL": "",
						"id": "",
						"name": "",
						"username": ""
					}
				},
				"otp": {
					"duration": 180,
					"emailTemplate": {
						"body": "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
						"subject": "OTP for {APP_NAME}"
					},
					"enabled": false,
					"length": 8
				},
				"passwordAuth": {
					"enabled": true,
					"identityFields": [
						"email"
					]
				},
				"passwordResetToken": {
					"duration": 1800
				},
				"resetPasswordTemplate": {
					"body": "<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Reset password</a>\n</p>\n<p><i>If you didn't ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
					"subject": "Reset your {APP_NAME} password"
				},
				"system": true,
				"type": "auth",
				"updateRule": null,
				"verificationTemplate": {
					"body": "<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
					"subject": "Verify your {APP_NAME} email"
				},
				"verificationToken": {
					"duration": 259200
				},
				"viewRule": null
			},
			{
				"authAlert": {
					"emailTemplate": {
						"body": "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location.</p>\n<p>If this was you, you may disregard this email.</p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
						"subject": "Login from a new location"
					},
					"enabled": true
				},
				"authRule": "",
				"authToken": {
					"duration": 604800
				},
				"confirmEmailChangeTemplate": {
					"body": "<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Confirm new email</a>\n</p>\n<p><i>If you didn't ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
					"subject": "Confirm your {APP_NAME} new email address"
				},
				"createRule": "",
				"deleteRule": "id = @request.auth.id",
				"emailChangeToken": {
					"duration": 1800
				},
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cost": 0,
						"hidden": true,
						"id": "password901924565",
						"max": 0,
						"min": 8,
						"name": "password",
						"pattern": "",
						"presentable": false,
						"required": true,
						"system": true,
						"type": "password"
					},
					{
						"autogeneratePattern": "[a-zA-Z0-9]{50}",
						"hidden": true,
						"id": "text2504183744",
						"max": 60,
						"min": 30,
						"name": "tokenKey",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"exceptDomains": null,
						"hidden": false,
						"id": "email3885137012",
						"name": "email",
						"onlyDomains": null,
						"presentable": false,
						"required": true,
						"system": true,
						"type": "email"
					},
					{
						"hidden": false,
						"id": "bool1547992806",
						"name": "emailVisibility",
						"presentable": false,
						"required": false,
						"system": true,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "bool256245529",
						"name": "verified",
						"presentable": false,
						"required": false,
						"system": true,
						"type": "bool"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1579384326",
						"max": 255,
						"min": 0,
						"name": "name",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "file376926767",
						"maxSelect": 1,
						"maxSize": 0,
						"mimeTypes": [
							"image/jpeg",
							"image/png",
							"image/svg+xml",
							"image/gif",
							"image/webp"
						],
						"name": "avatar",
						"presentable": false,
						"protected": false,
						"required": false,
						"system": false,
						"thumbs": null,
						"type": "file"
					},
					{
						"hidden": false,
						"id": "number4115522831",
						"max": null,
						"min": null,
						"name": "height",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number130897217",
						"max": null,
						"min": null,
						"name": "weight",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "date4047949298",
						"max": "",
						"min": "",
						"name": "dob",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "date"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"fileToken": {
					"duration": 180
				},
				"id": "_pb_users_auth_",
				"indexes": [
					"CREATE UNIQUE INDEX ` + "`" + `idx_tokenKey__pb_users_auth_` + "`" + ` ON ` + "`" + `users` + "`" + ` (` + "`" + `tokenKey` + "`" + `)",
					"CREATE UNIQUE INDEX ` + "`" + `idx_email__pb_users_auth_` + "`" + ` ON ` + "`" + `users` + "`" + ` (` + "`" + `email` + "`" + `) WHERE ` + "`" + `email` + "`" + ` != ''"
				],
				"listRule": "id = @request.auth.id",
				"manageRule": null,
				"mfa": {
					"duration": 1800,
					"enabled": false,
					"rule": ""
				},
				"name": "users",
				"oauth2": {
					"enabled": true,
					"mappedFields": {
						"avatarURL": "avatar",
						"id": "",
						"name": "name",
						"username": ""
					}
				},
				"otp": {
					"duration": 180,
					"emailTemplate": {
						"body": "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
						"subject": "OTP for {APP_NAME}"
					},
					"enabled": false,
					"length": 8
				},
				"passwordAuth": {
					"enabled": true,
					"identityFields": [
						"email"
					]
				},
				"passwordResetToken": {
					"duration": 1800
				},
				"resetPasswordTemplate": {
					"body": "<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Reset password</a>\n</p>\n<p><i>If you didn't ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
					"subject": "Reset your {APP_NAME} password"
				},
				"system": false,
				"type": "auth",
				"updateRule": "id = @request.auth.id",
				"verificationTemplate": {
					"body": "<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
					"subject": "Verify your {APP_NAME} email"
				},
				"verificationToken": {
					"duration": 259200
				},
				"viewRule": "id = @request.auth.id"
			},
			{
				"createRule": "",
				"deleteRule": "createdBy=@request.auth.id",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "bool3377271179",
						"name": "system",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"cascadeDelete": false,
						"collectionId": "_pb_users_auth_",
						"hidden": false,
						"id": "relation3545646658",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "createdBy",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1579384326",
						"max": 0,
						"min": 0,
						"name": "name",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "bool1201773643",
						"name": "numeric",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "bool1001664029",
						"name": "public",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1731158936",
						"max": 0,
						"min": 0,
						"name": "displayName",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_2821557499",
				"indexes": [],
				"listRule": "createdBy=@request.auth.id || public=true",
				"name": "measurementTypes",
				"system": false,
				"type": "base",
				"updateRule": "createdBy=@request.auth.id",
				"viewRule": "createdBy=@request.auth.id || public=true"
			},
			{
				"createRule": "measurementType.createdBy=@request.auth.id",
				"deleteRule": "measurementType.createdBy=@request.auth.id",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2821557499",
						"hidden": false,
						"id": "relation729101162",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "measurementType",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text494360628",
						"max": 0,
						"min": 0,
						"name": "value",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "_pb_users_auth_",
						"hidden": false,
						"id": "relation3545646658",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "createdBy",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "bool1001664029",
						"name": "public",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_920668891",
				"indexes": [],
				"listRule": "measurementType.createdBy=@request.auth.id || public=true",
				"name": "measurementValues",
				"system": false,
				"type": "base",
				"updateRule": "measurementType.createdBy=@request.auth.id",
				"viewRule": "measurementType.createdBy=@request.auth.id || public=true"
			},
			{
				"createRule": "",
				"deleteRule": "createdBy=@request.auth.id",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "_pb_users_auth_",
						"hidden": false,
						"id": "relation2375276105",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "createdBy",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1579384326",
						"max": 0,
						"min": 0,
						"name": "name",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1843675174",
						"max": 0,
						"min": 0,
						"name": "description",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "bool773602581",
						"name": "bodyweight",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2821557499",
						"hidden": false,
						"id": "relation729101162",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "defaultMeasurementType",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "_pb_users_auth_",
						"hidden": false,
						"id": "relation2861482548",
						"maxSelect": 999,
						"minSelect": 0,
						"name": "usersSaved",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "bool1001664029",
						"name": "public",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "bool3377271179",
						"name": "system",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2821557499",
						"hidden": false,
						"id": "relation849136569",
						"maxSelect": 999,
						"minSelect": 0,
						"name": "allowedMeasurementTypes",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2821557499",
						"hidden": false,
						"id": "relation1160476469",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "defaultMeasurementType2",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2821557499",
						"hidden": false,
						"id": "relation3665259660",
						"maxSelect": 999,
						"minSelect": 0,
						"name": "allowedMeasurementTypes2",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2821557499",
						"hidden": false,
						"id": "relation841762723",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "defaultMeasurementType3",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2821557499",
						"hidden": false,
						"id": "relation2909821978",
						"maxSelect": 999,
						"minSelect": 0,
						"name": "allowedMeasurementTypes3",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "file3309110367",
						"maxSelect": 1,
						"maxSize": 0,
						"mimeTypes": [],
						"name": "image",
						"presentable": false,
						"protected": false,
						"required": false,
						"system": false,
						"thumbs": [],
						"type": "file"
					},
					{
						"hidden": false,
						"id": "file2093472300",
						"maxSelect": 1,
						"maxSize": 0,
						"mimeTypes": [],
						"name": "video",
						"presentable": false,
						"protected": false,
						"required": false,
						"system": false,
						"thumbs": [],
						"type": "file"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text2575139115",
						"max": 0,
						"min": 0,
						"name": "instructions",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "select3144380399",
						"maxSelect": 1,
						"name": "difficulty",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Novice",
							"Beginner",
							"Intermediate",
							"Advanced",
							"Expert",
							"Master",
							"Grand Master",
							"Legendary"
						]
					},
					{
						"hidden": false,
						"id": "relation3738894301",
						"maxSelect": 1,
						"name": "targetMuscleGroup",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Trapezius",
							"Abductors",
							"Glutes",
							"Adductors",
							"Chest",
							"Forearms",
							"Shins",
							"Hip Flexors",
							"Triceps",
							"Calves",
							"Biceps",
							"Quadriceps",
							"Hamstrings",
							"Shoulders",
							"Abdominals",
							"Back"
						]
					},
					{
						"hidden": false,
						"id": "relation3231338956",
						"maxSelect": 1,
						"name": "musclePrimary",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Gluteus Medius",
							"Pectoralis Major",
							"Adductor Magnus",
							"Anterior Deltoids",
							"Subscapularis",
							"Gluteus Maximus",
							"Erector Spinae",
							"Triceps Brachii",
							"Upper Trapezius",
							"Iliopsoas",
							"Soleus",
							"Rectus Abdominis",
							"Infraspinatus",
							"Biceps Brachii",
							"Lateral Deltoids",
							"Latissimus Dorsi",
							"Vastus Mediais",
							"Biceps Femoris",
							"Quadriceps Femoris",
							"Tibialis Anterior",
							"Posterior Deltoids",
							"Brachioradialis",
							"Obliques",
							"Gastrocnemius"
						]
					},
					{
						"hidden": false,
						"id": "relation1299607105",
						"maxSelect": 1,
						"name": "muscleSecondary",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Gluteus Medius",
							"Teres Major",
							"Rectus Femoris",
							"Pectoralis Major",
							"Adductor Magnus",
							"Brachialis",
							"Anterior Deltoids",
							"Subscapularis",
							"Rhomboids",
							"Gluteus Maximus",
							"Iliopsoas",
							"Triceps Brachii",
							"Soleus",
							"Rectus Abdominis",
							"Levator Scapulae",
							"Infraspinatus",
							"Biceps Brachii",
							"Latissimus Dorsi",
							"Biceps Femoris",
							"Extensor Digitorum Longus",
							"Quadriceps Femoris",
							"Supraspinatus",
							"Anconeus",
							"Medial Deltoids",
							"Posterior Deltoids",
							"Brachioradialis",
							"Obliques",
							"Gluteus Minimus",
							"Gastrocnemius"
						]
					},
					{
						"hidden": false,
						"id": "relation1933276611",
						"maxSelect": 1,
						"name": "muscleTertiary",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Trapezius",
							"Gluteus Medius",
							"Teres Major",
							"Rectus Femoris",
							"Pectoralis Major",
							"Adductor Magnus",
							"Brachialis",
							"Anterior Deltoids",
							"Rhomboids",
							"Gluteus Maximus",
							"Tensor Fasciae Latae",
							"Erector Spinae",
							"Iliopsoas",
							"Upper Trapezius",
							"Triceps Brachii",
							"Soleus",
							"Transverse Abdominis",
							"Rectus Abdominis",
							"Biceps Brachii",
							"Latissimus Dorsi",
							"Biceps Femoris",
							"Quadriceps Femoris",
							"Tibialis Anterior",
							"Gastrocnemius",
							"Flexor Carpi Radialis",
							"Posterior Deltoids",
							"Brachioradialis",
							"Obliques",
							"Gluteus Minimus",
							"Extensor Hallucis Longus",
							"Teres Minor",
							"Serratus Anterior",
							"Tibialis Posterior"
						]
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2447119828",
						"hidden": false,
						"id": "relation2252688345",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "equipmentPrimary",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2447119828",
						"hidden": false,
						"id": "relation2275489776",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "equipmentSecondary",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "select2690792214",
						"maxSelect": 1,
						"name": "posture",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Walking",
							"Split Squat",
							"Half Kneeling",
							"Staggered Stance",
							"Inverted",
							"Standing",
							"Seated Floor",
							"Quadruped",
							"Tuck L Sit",
							"Side Lying",
							"Hanging",
							"Toe Balance",
							"Isometric Split Squat",
							"Side Plank",
							"Single Leg Standing Bent Knee",
							"Shin Box Seated",
							"Horse Stance",
							"L Sit",
							"Single Leg Supported",
							"Knee Over Toe Split Squat",
							"Knee Hover Quadruped",
							"March",
							"90/90 Seated",
							"Tall Kneeling",
							"Knee Supported",
							"Single Leg Bridge",
							"Supine",
							"Running",
							"Bridge",
							"Prone",
							"Single Leg Standing",
							"Seated",
							"Wall Sit",
							"V Sit Seated",
							"Other",
							"Kneeling"
						]
					},
					{
						"hidden": false,
						"id": "select885276337",
						"maxSelect": 1,
						"name": "armCount",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Double Arm",
							"No Arms",
							"Single Arm"
						]
					},
					{
						"hidden": false,
						"id": "select3111732077",
						"maxSelect": 1,
						"name": "armPattern",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Continuous",
							"Alternating"
						]
					},
					{
						"hidden": false,
						"id": "select888802634",
						"maxSelect": 1,
						"name": "grip",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Flat Palm",
							"Fingertip",
							"Bottoms Up",
							"Mixed Grip",
							"Supinated",
							"Waiter Hold",
							"Crush Grip",
							"Horn Grip",
							"False Grip",
							"Neutral",
							"Forearm",
							"Hand Assisted",
							"Other",
							"Goblet",
							"Bottoms Up Horn Grip",
							"No Grip",
							"Head Supported",
							"Pronated"
						]
					},
					{
						"hidden": false,
						"id": "select1022487629",
						"maxSelect": 1,
						"name": "endLoadPosition",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Order",
							"Overhead",
							"Behind Back",
							"Low Hold",
							"Lateral",
							"Shoulder",
							"Zercher",
							"Bear Hug",
							"Above Chest",
							"Hip Crease",
							"Other",
							"No Load",
							"Back Rack",
							"Front Rack",
							"Suitcase"
						]
					},
					{
						"hidden": false,
						"id": "select367459245",
						"maxSelect": 1,
						"name": "legPattern",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Continuous",
							"Alternating"
						]
					},
					{
						"hidden": false,
						"id": "select2683841512",
						"maxSelect": 1,
						"name": "footElevation",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Toes Elevated",
							"Feet Elevated",
							"Foot Elevated",
							"Foot Elevated (Rear)",
							"No Elevation",
							"Foot Elevated (Side)",
							"Heels Elevated",
							"Foot Elevated (Front)",
							"Foot Elevated (Lateral)"
						]
					},
					{
						"hidden": false,
						"id": "bool3872711076",
						"name": "isCombination",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "text4161961133",
						"maxSelect": 1,
						"name": "movementPattern",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Wrist Extension",
							"Horizontal Pull",
							"Locomotion",
							"Hip Dominant",
							"Knee Dominant",
							"Horizontal Push",
							"Shoulder Flexion",
							"Shoulder Internal Rotation",
							"Ankle Dorsiflexion",
							"Shoulder Abduction",
							"Anti-Extension",
							"Anti-Lateral Flexion",
							"Loaded Carry",
							"Lateral Flexion",
							"Scapular Elevation",
							"Elbow Flexion",
							"Rotational",
							"Hip External Rotation",
							"Horizontal Adduction",
							"Hip Hinge",
							"Shoulder External Rotation",
							"Lateral Locomotion",
							"Ankle Plantar Flexion",
							"Spinal Extension",
							"Hip Extension",
							"Hip Flexion",
							"Anti-Rotational",
							"Hip Abduction",
							"Hip Adduction",
							"Vertical Push",
							"Wrist Flexion",
							"Anti-Flexion",
							"Isometric Hold",
							"Vertical Pull",
							"Elbow Extension",
							"Shoulder Scapular Plane Elevation",
							"Spinal Flexion"
						]
					},
					{
						"hidden": false,
						"id": "text2991223588",
						"maxSelect": 1,
						"name": "movementPattern2",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Hip Extension",
							"Anti-Rotational",
							"Hip External Rotation",
							"Hip Hinge",
							"Hip Abduction",
							"Anti-Extension",
							"Anti-Lateral Flexion",
							"Horizontal Push",
							"Vertical Push",
							"Horizontal Pull",
							"Spinal Rotational",
							"Isometric Hold",
							"Knee Dominant",
							"Other",
							"Elbow Flexion",
							"Spinal Flexion",
							"Rotational"
						]
					},
					{
						"hidden": false,
						"id": "text3310175154",
						"maxSelect": 1,
						"name": "movementPattern3",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Hip Hinge",
							"Anti-Extension",
							"Anti-Lateral Flexion",
							"Vertical Push",
							"Horizontal Pull",
							"Hip Internal Rotation",
							"Isometric Hold",
							"Knee Dominant"
						]
					},
					{
						"hidden": false,
						"id": "select999341016",
						"maxSelect": 1,
						"name": "motionPlane",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Sagittal Plane",
							"Transverse Plane",
							"Frontal Plane"
						]
					},
					{
						"hidden": false,
						"id": "select2464576592",
						"maxSelect": 1,
						"name": "motionPlane2",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Sagittal Plane",
							"Transverse Plane",
							"Frontal Plane"
						]
					},
					{
						"hidden": false,
						"id": "select3856745670",
						"maxSelect": 1,
						"name": "motionPlane3",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Sagittal Plane"
						]
					},
					{
						"hidden": false,
						"id": "select555719700",
						"maxSelect": 1,
						"name": "bodyRegion",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Core",
							"Full Body",
							"Upper Body",
							"Lower Body"
						]
					},
					{
						"hidden": false,
						"id": "select1767259479",
						"maxSelect": 1,
						"name": "forceType",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Push",
							"Pull",
							"Other",
							"Push & Pull"
						]
					},
					{
						"hidden": false,
						"id": "select849752397",
						"maxSelect": 1,
						"name": "mechanics",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Pull",
							"Compound",
							"Isolation"
						]
					},
					{
						"hidden": false,
						"id": "select605673998",
						"maxSelect": 1,
						"name": "laterality",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Contralateral",
							"Bilateral",
							"Unilateral",
							"Ipsilateral"
						]
					},
					{
						"hidden": false,
						"id": "select1542800728",
						"maxSelect": 1,
						"name": "field",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"Powerlifting",
							"Postural",
							"Bodybuilding",
							"Ballistics",
							"Mobility",
							"Grinds",
							"Calisthenics",
							"Plyometric",
							"Balance",
							"Olympic Weightlifting",
							"Animal Flow"
						]
					},
					{
						"hidden": false,
						"id": "booltime711034",
						"name": "isTimeBased",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_1804250889",
				"indexes": [
					"CREATE UNIQUE INDEX ` + "`" + `idx_6Zbgk09etr` + "`" + ` ON ` + "`" + `exercises` + "`" + ` (\n  ` + "`" + `name` + "`" + `,\n  ` + "`" + `createdBy` + "`" + `\n)"
				],
				"listRule": "createdBy=@request.auth.id || public=true",
				"name": "exercises",
				"system": false,
				"type": "base",
				"updateRule": "createdBy=@request.auth.id",
				"viewRule": "createdBy=@request.auth.id || public=true"
			},
			{
				"createRule": "",
				"deleteRule": "user=@request.auth.id",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1579384326",
						"max": 0,
						"min": 0,
						"name": "name",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "_pb_users_auth_",
						"hidden": false,
						"id": "relation2375276105",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "user",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text482507221",
						"max": 0,
						"min": 0,
						"name": "userDay",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text18589324",
						"max": 0,
						"min": 0,
						"name": "notes",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "number2585524221",
						"max": null,
						"min": null,
						"name": "userHeight",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1755006899",
						"max": null,
						"min": null,
						"name": "userWeight",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_1219621782",
						"hidden": false,
						"id": "relation1874629670",
						"maxSelect": 999,
						"minSelect": 0,
						"name": "tags",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "select3519473193",
						"maxSelect": 1,
						"name": "sleepQuality",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "select",
						"values": [
							"terrible",
							"poor",
							"fair",
							"good",
							"great"
						]
					},
					{
						"hidden": false,
						"id": "json1847681537",
						"maxSize": 0,
						"name": "exercisesOrder",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "json"
					},
					{
						"hidden": false,
						"id": "json4266430727",
						"maxSize": 0,
						"name": "mealsOrder",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "json"
					},
					{
						"hidden": false,
						"id": "number319486758",
						"max": 5,
						"min": 0,
						"name": "stressRating",
						"onlyInt": true,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1570253453",
						"max": 5,
						"min": 0,
						"name": "anxietyRating",
						"onlyInt": true,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1553789333",
						"max": 5,
						"min": 0,
						"name": "moodRating",
						"onlyInt": true,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "date2921333693",
						"max": "",
						"min": "",
						"name": "timeStart",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "date"
					},
					{
						"hidden": false,
						"id": "date1731930",
						"max": "",
						"min": "",
						"name": "timeEnd",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "date"
					},
					{
						"hidden": false,
						"id": "number431587761",
						"max": null,
						"min": 0,
						"name": "sessionDuration",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_415974452",
				"indexes": [
					"CREATE UNIQUE INDEX ` + "`" + `idx_LvIRQtjNTo` + "`" + ` ON ` + "`" + `sessions` + "`" + ` (\n  ` + "`" + `user` + "`" + `,\n  ` + "`" + `userDay` + "`" + `\n)"
				],
				"listRule": "user=@request.auth.id",
				"name": "sessions",
				"system": false,
				"type": "base",
				"updateRule": "user=@request.auth.id",
				"viewRule": "user=@request.auth.id"
			},
			{
				"createRule": "",
				"deleteRule": null,
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1579384326",
						"max": 0,
						"min": 0,
						"name": "name",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "_pb_users_auth_",
						"hidden": false,
						"id": "relation2375276105",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "createdBy",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "bool1001664029",
						"name": "public",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text3674716419",
						"max": 0,
						"min": 0,
						"name": "colorHex",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_1219621782",
				"indexes": [
					"CREATE UNIQUE INDEX ` + "`" + `idx_0WYODMk6hz` + "`" + ` ON ` + "`" + `tags` + "`" + ` (\n  ` + "`" + `name` + "`" + `,\n  ` + "`" + `createdBy` + "`" + `\n)"
				],
				"listRule": "createdBy=@request.auth.id || public=true",
				"name": "tags",
				"system": false,
				"type": "base",
				"updateRule": "createdBy=@request.auth.id",
				"viewRule": "createdBy=@request.auth.id || public=true"
			},
			{
				"createRule": "session.user=@request.auth.id",
				"deleteRule": "session.user=@request.auth.id",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_1804250889",
						"hidden": false,
						"id": "relation2933576988",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "exercise",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text18589324",
						"max": 0,
						"min": 0,
						"name": "notes",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_1219621782",
						"hidden": false,
						"id": "relation1874629670",
						"maxSelect": 999,
						"minSelect": 0,
						"name": "tags",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "number1963965259",
						"max": null,
						"min": null,
						"name": "addedWeight",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1673740827",
						"max": null,
						"min": null,
						"name": "restAfter",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1978170294",
						"max": null,
						"min": null,
						"name": "measurementNumeric",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number2381468880",
						"max": null,
						"min": null,
						"name": "measurement2Numeric",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1096307790",
						"max": null,
						"min": null,
						"name": "measurement3Numeric",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_920668891",
						"hidden": false,
						"id": "relation4060472186",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "measurementValue",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_920668891",
						"hidden": false,
						"id": "relation1958976562",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "measurement2Value",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_920668891",
						"hidden": false,
						"id": "relation3214888855",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "measurement3Value",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_1563017532",
						"hidden": false,
						"id": "relation3589910472",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "supersetParent",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "bool1101726742",
						"name": "isWarmup",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "number1794094383",
						"max": 150,
						"min": 0,
						"name": "perceivedEffort",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"cascadeDelete": true,
						"collectionId": "pbc_415974452",
						"hidden": false,
						"id": "relation2207781110",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "session",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "number1984494829",
						"max": 100,
						"min": 0,
						"name": "enduranceRating",
						"onlyInt": true,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number3716291499",
						"max": 100,
						"min": 0,
						"name": "strengthRating",
						"onlyInt": true,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "date2921333693",
						"max": "",
						"min": "",
						"name": "timeStart",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "date"
					},
					{
						"hidden": false,
						"id": "date1731930",
						"max": "",
						"min": "",
						"name": "timeEnd",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "date"
					},
					{
						"hidden": false,
						"id": "number3514102958",
						"max": null,
						"min": null,
						"name": "exerciseDuration",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_1563017532",
				"indexes": [],
				"listRule": "session.user=@request.auth.id",
				"name": "sessionExercises",
				"system": false,
				"type": "base",
				"updateRule": "session.user=@request.auth.id",
				"viewRule": "session.user=@request.auth.id"
			},
			{
				"createRule": "",
				"deleteRule": "session.user=@request.auth.id",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1579384326",
						"max": 0,
						"min": 0,
						"name": "name",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "number1790388437",
						"max": null,
						"min": null,
						"name": "kj",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number4205719620",
						"max": null,
						"min": null,
						"name": "gramsProtein",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1554591994",
						"max": null,
						"min": null,
						"name": "gramsCarbohydrate",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1088604425",
						"max": null,
						"min": null,
						"name": "gramsFat",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"cascadeDelete": true,
						"collectionId": "pbc_415974452",
						"hidden": false,
						"id": "relation2207781110",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "session",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_1219621782",
						"hidden": false,
						"id": "relation1874629670",
						"maxSelect": 999,
						"minSelect": 0,
						"name": "tags",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1843675174",
						"max": 0,
						"min": 0,
						"name": "description",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "bool4192457509",
						"name": "saved",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_695162881",
				"indexes": [],
				"listRule": "session.user=@request.auth.id",
				"name": "sessionMeals",
				"system": false,
				"type": "base",
				"updateRule": "session.user=@request.auth.id",
				"viewRule": "session.user=@request.auth.id"
			},
			{
				"createRule": "",
				"deleteRule": "user=@request.auth.id",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1579384326",
						"max": 0,
						"min": 0,
						"name": "name",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": false,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "_pb_users_auth_",
						"hidden": false,
						"id": "relation2375276105",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "user",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text18589324",
						"max": 0,
						"min": 0,
						"name": "description",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "json1638960659",
						"maxSize": 0,
						"name": "exercisesOrder",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "json"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_884676139",
				"indexes": [],
				"listRule": "user=@request.auth.id",
				"name": "routines",
				"system": false,
				"type": "base",
				"updateRule": "user=@request.auth.id",
				"viewRule": "user=@request.auth.id"
			},
			{
				"createRule": "routine.user=@request.auth.id",
				"deleteRule": "routine.user=@request.auth.id",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cascadeDelete": true,
						"collectionId": "pbc_884676139",
						"hidden": false,
						"id": "relation1274468566",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "routine",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_1804250889",
						"hidden": false,
						"id": "relation2933576988",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "exercise",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text18589324",
						"max": 0,
						"min": 0,
						"name": "notes",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_1219621782",
						"hidden": false,
						"id": "relation1874629670",
						"maxSelect": 999,
						"minSelect": 0,
						"name": "tags",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "number1963965259",
						"max": null,
						"min": null,
						"name": "addedWeight",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1673740827",
						"max": null,
						"min": null,
						"name": "restAfter",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1978170294",
						"max": null,
						"min": null,
						"name": "measurementNumeric",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number2381468880",
						"max": null,
						"min": null,
						"name": "measurement2Numeric",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number1096307790",
						"max": null,
						"min": null,
						"name": "measurement3Numeric",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_920668891",
						"hidden": false,
						"id": "number4060472186",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "measurementValue",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_920668891",
						"hidden": false,
						"id": "number1958976562",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "measurement2Value",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_920668891",
						"hidden": false,
						"id": "number3214888855",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "measurement3Value",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "bool1101726742",
						"name": "isWarmup",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "duration1654338838",
						"max": null,
						"min": 0,
						"name": "targetDuration",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_1139529185",
						"hidden": false,
						"id": "relation3589910472",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "supersetParent",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "number1984494829",
						"max": 100,
						"min": 0,
						"name": "enduranceRating",
						"onlyInt": true,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number3716291499",
						"max": 100,
						"min": 0,
						"name": "strengthRating",
						"onlyInt": true,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "number3514102958",
						"max": null,
						"min": null,
						"name": "exerciseDuration",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_1139529185",
				"indexes": [],
				"listRule": "routine.user=@request.auth.id",
				"name": "routineExercises",
				"system": false,
				"type": "base",
				"updateRule": "routine.user=@request.auth.id",
				"viewRule": "routine.user=@request.auth.id"
			},
			{
				"createRule": null,
				"deleteRule": null,
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1579384326",
						"max": 0,
						"min": 0,
						"name": "name",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": true,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_2447119828",
				"indexes": [],
				"listRule": "",
				"name": "equipments",
				"system": false,
				"type": "base",
				"updateRule": null,
				"viewRule": ""
			},
			{
				"createRule": "",
				"deleteRule": "user = @request.auth.id",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "_pb_users_auth_",
						"hidden": false,
						"id": "relation2375276105",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "user",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": true,
						"collectionId": "pbc_1804250889",
						"hidden": false,
						"id": "relation2933576988",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "exercise",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text18589324",
						"max": 0,
						"min": 0,
						"name": "notes",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "saved3289324",
						"name": "saved",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_1219621782",
						"hidden": false,
						"id": "relation1874629670",
						"maxSelect": 999,
						"minSelect": 0,
						"name": "tags",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_2821557499",
						"hidden": false,
						"id": "relation2839008875",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "preferredMeasurementType",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_203563952",
				"indexes": [
					"CREATE UNIQUE INDEX ` + "`" + `idx_pwDyO5G2iD` + "`" + ` ON ` + "`" + `exercisePreferences` + "`" + ` (\n  ` + "`" + `user` + "`" + `,\n  ` + "`" + `exercise` + "`" + `\n)"
				],
				"listRule": "user = @request.auth.id",
				"name": "exercisePreferences",
				"system": false,
				"type": "base",
				"updateRule": "user = @request.auth.id",
				"viewRule": "user = @request.auth.id"
			}
		]`

		return app.ImportCollectionsByMarshaledJSON([]byte(jsonData), false)
	}, func(app core.App) error {
		return nil
	})
}
